from docx import Document
from docx.shared import Inches
import pyttsx3

def speak(text):
    pyttsx3.speak(text)

document = Document()

# profile picture
document.add_picture(
    'profile2.jpg',
     width=Inches(2.0)
     )
# name phone number and email details
name = input('What is your name? ')
speak('Hello ' + name +' how are you doing?')

phone_number = input('What is your phone number? ')
email =input('What is your email? ')

document.add_paragraph(
    name+'|'+ phone_number+'|'+email)

# about me
document.add_heading('About me')
document.add_paragraph(input('Tell me about yourself? '))

#work experience
document.add_heading('Work experience')
p = document.add_paragraph()

company = input('Enter company ')
from_date = input('From date ')
to_date = input('To date ')

p.add_run(company +  ' ').bold = True
p.add_run(from_date +'-'+ to_date + '\n').italic = True

experience_details= input(
    'Describe your experience at '+ company+' ')
p.add_run(experience_details)


# more experiences
while True:
    has_more_experiences = input(
        'Do you have more experiences ? Yes or No ')
    if has_more_experiences.lower() == 'yes':
        p = document.add_paragraph()

        company = input('Enter company ')
        from_date = input('From date ')
        to_date = input('To date ')

        p.add_run(company +  ' ').bold = True
        p.add_run(from_date +'-'+ to_date + '\n').italic = True

        experience_details= input(
            'Describe your experience at '+ company)
        p.add_run(experience_details)
    else:
        break

# Skills
document.add_heading('Skills')
document.add_paragraph(input('Enter your skill '), style = 'List Bullet')

while True:
    if input('Do you want to add more skills ?  Yes or No '
    ).lower() == 'yes':
       document.add_paragraph(input('Enter your skill '), style = 'List Bullet')
    else:
        break

# Footer
section = document.sections[0]
footer = section.footer
p = footer.paragraphs[0]
p.text = "Cv generated by Stefan"

document.save('cv.docx')